name: Flow

on: [push]

jobs:
  Base:
    runs-on: runner
    steps:
      - name: checkout code
        uses: https://eoelab.org:1027/actions/checkout@v4
      - name: base build
        uses: https://eoelab.org:1027/actions/build-push-action@v6
        with:
          context: base/cpu
          tags: eoelab.org:1027/${{ gitea.repository }}:base

  CUDA_Base:
    runs-on: runner
    steps:
      - name: checkout code
        uses: https://eoelab.org:1027/actions/checkout@v4
      - name: CUDA_Base build
        uses: https://eoelab.org:1027/actions/build-push-action@v6
        with:
          context: base/cuda/base
          build-args: |
            DEBIAN_MIRROR=mirrors.ustc.edu.cn
          tags: eoelab.org:1027/${{ gitea.repository }}:cuda_base
  
  CUDA_Runtime:
    runs-on: runner
    needs: CUDA_Base
    steps:
      - name: checkout code
        uses: https://eoelab.org:1027/actions/checkout@v4
      - name: CUDA_Runtime build
        uses: https://eoelab.org:1027/actions/build-push-action@v6
        with:
          context: base/cuda/runtime
          tags: eoelab.org:1027/${{ gitea.repository }}:cuda_runtime

  CUDA_Devel:
    runs-on: runner
    needs: CUDA_Runtime
    steps:
      - name: checkout code
        uses: https://eoelab.org:1027/actions/checkout@v4
      - name: CUDA_Devel build
        uses: https://eoelab.org:1027/actions/build-push-action@v6
        with:
          context: base/cuda/devel
          tags: eoelab.org:1027/${{ gitea.repository }}:cuda_devel

  ROCM:
    runs-on: runner
    steps:
      - name: checkout code
        uses: https://eoelab.org:1027/actions/checkout@v4
      - name: ROCM build
        uses: https://eoelab.org:1027/actions/build-push-action@v6
        with:
          context: base/rocm
          build-args: |
            UBUNTU_MIRROR=mirrors.ustc.edu.cn
            http_proxy=http://192.168.2.2:7890
            https_proxy=http://192.168.2.2:7890      
          tags: eoelab.org:1027/${{ gitea.repository }}:rocm

  C:
    runs-on: runner
    needs: Base
    steps:
      - name: checkout code
        uses: https://eoelab.org:1027/actions/checkout@v4
      - name: c build
        uses: https://eoelab.org:1027/actions/build-push-action@v6
        with:
          context: Program/c
          tags: eoelab.org:1027/${{ gitea.repository }}:c

  Cpp:
    runs-on: runner
    needs: Base
    steps:
      - name: checkout code
        uses: https://eoelab.org:1027/actions/checkout@v4
      - name: cpp build
        uses: https://eoelab.org:1027/actions/build-push-action@v6
        with:
          context: Program/cpp
          tags: eoelab.org:1027/${{ gitea.repository }}:cpp

  JDK:
    runs-on: runner
    needs: Base
    steps:
      - name: checkout code
        uses: https://eoelab.org:1027/actions/checkout@v4
      - name: java build
        uses: https://eoelab.org:1027/actions/build-push-action@v6
        with:
          context: Program/java/jdk
          tags: eoelab.org:1027/${{ gitea.repository }}:jdk

  JRE:
    runs-on: runner
    needs: Base
    steps:
      - name: checkout code
        uses: https://eoelab.org:1027/actions/checkout@v4
      - name: jre build
        uses: https://eoelab.org:1027/actions/build-push-action@v6
        with:
          context: Program/java/jre
          tags: eoelab.org:1027/${{ gitea.repository }}:jre


  JS:
    runs-on: runner
    needs: Base
    steps:
      - name: checkout code
        uses: https://eoelab.org:1027/actions/checkout@v4
      - name: js build
        uses: https://eoelab.org:1027/actions/build-push-action@v6
        with:
          context: Program/js
          tags: eoelab.org:1027/${{ gitea.repository }}:js

  Hexo:
    runs-on: runner
    needs: JS
    steps:
      - name: checkout code
        uses: https://eoelab.org:1027/actions/checkout@v4
      - name: hexo build
        uses: https://eoelab.org:1027/actions/build-push-action@v6
        with:
          context: Renv/hexo
          tags: eoelab.org:1027/${{ gitea.repository }}:hexo

  Python:
    runs-on: runner
    needs: Base
    steps:
      - name: checkout code
        uses: https://eoelab.org:1027/actions/checkout@v4
      - name: python build
        uses: https://eoelab.org:1027/actions/build-push-action@v6
        with:
          context: Program/python
          tags: eoelab.org:1027/${{ gitea.repository }}:python

  Jupyterlite:
    runs-on: runner
    needs: Python
    steps:
      - name: checkout code
        uses: https://eoelab.org:1027/actions/checkout@v4
      - name: jupyterlite build
        uses: https://eoelab.org:1027/actions/build-push-action@v6
        with:
          context: Renv/jupyterlite
          tags: eoelab.org:1027/${{ gitea.repository }}:jupyterlite

  Julia:
    runs-on: runner
    needs: Python
    steps:
      - name: checkout code
        uses: https://eoelab.org:1027/actions/checkout@v4
      - name: julia build
        uses: https://eoelab.org:1027/actions/build-push-action@v6
        with:
          context: Program/julia
          tags: eoelab.org:1027/${{ gitea.repository }}:julia

  R:
    runs-on: runner
    needs: Base
    steps:
      - name: checkout code
        uses: https://eoelab.org:1027/actions/checkout@v4
      - name: r build
        uses: https://eoelab.org:1027/actions/build-push-action@v6
        with:
          context: Program/r
          tags: eoelab.org:1027/${{ gitea.repository }}:r
  
  MC_BE:
    runs-on: runner
    needs: Base
    steps:
      - name: checkout code
        uses: https://eoelab.org:1027/actions/checkout@v4
      - name: mc_be build
        uses: https://eoelab.org:1027/actions/build-push-action@v6
        with:
          context: GS/mc/be
          tags: eoelab.org:1027/${{ gitea.repository }}:mc_be

  MC_JRE_8:
    runs-on: runner
    needs: Base
    steps:
      - name: checkout code
        uses: https://eoelab.org:1027/actions/checkout@v4
      - name: mc_jre_8 build
        uses: https://eoelab.org:1027/actions/build-push-action@v6
        with:
          context: GS/mc/jre/8
          tags: eoelab.org:1027/${{ gitea.repository }}:mc_jre_8

  MC_JRE_11:
    runs-on: runner
    needs: Base
    steps:
      - name: checkout code
        uses: https://eoelab.org:1027/actions/checkout@v4
      - name: mc_jre_11 build
        uses: https://eoelab.org:1027/actions/build-push-action@v6
        with:
          context: GS/mc/jre/11
          tags: eoelab.org:1027/${{ gitea.repository }}:mc_jre_11

  MC_JRE_17:
    runs-on: runner
    needs: Base
    steps:
      - name: checkout code
        uses: https://eoelab.org:1027/actions/checkout@v4
      - name: mc_jre_17 build
        uses: https://eoelab.org:1027/actions/build-push-action@v6
        with:
          context: GS/mc/jre/17
          tags: eoelab.org:1027/${{ gitea.repository }}:mc_jre_17

  MC_JRE_21:
    runs-on: runner
    needs: Base
    steps:
      - name: checkout code
        uses: https://eoelab.org:1027/actions/checkout@v4
      - name: mc_jre_21 build
        uses: https://eoelab.org:1027/actions/build-push-action@v6
        with:
          context: GS/mc/jre/21
          tags: eoelab.org:1027/${{ gitea.repository }}:mc_jre_21

  Steam:
    runs-on: runner
    needs: Base
    steps:
      - name: checkout code
        uses: https://eoelab.org:1027/actions/checkout@v4
      - name: steam build
        uses: https://eoelab.org:1027/actions/build-push-action@v6
        with:
          context: GS/steam
          build-args: |
            http_proxy=http://192.168.2.2:7890
            https_proxy=http://192.168.2.2:7890
          tags: eoelab.org:1027/${{ gitea.repository }}:steam

  Steam_Wine:
    runs-on: runner
    needs: Steam
    steps:
      - name: checkout code
        uses: https://eoelab.org:1027/actions/checkout@v4
      - name: steam_wine build
        uses: https://eoelab.org:1027/actions/build-push-action@v6
        with:
          context: GS/steam/steam_wine
          tags: eoelab.org:1027/${{ gitea.repository }}:steam_wine

  LLAMA:
    runs-on: runner
    needs: Base
    steps:
      - name: checkout code
        uses: https://eoelab.org:1027/actions/checkout@v4
      - name: llama build
        uses: https://eoelab.org:1027/actions/build-push-action@v6
        with:
          context: Renv/llama
          tags: eoelab.org:1027/${{ gitea.repository }}:llama


  Push:
    runs-on: runner
    needs: [Steam_Wine,CUDA_Devel]
    steps:
      - name: login gitea_registry
        uses: https://eoelab.org:1027/actions/login-action@v3
        with:
          registry: eoelab.org:1027
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWD }}
      - name: push images to gitea_registry
        run: docker image push "eoelab.org:1027/${{ gitea.repository }}" --all-tags